# Using tasks from the 'Azure DevOps Extension Tasks' extension:
# https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks

name: 0.0.$(Rev:r)

trigger:
- master

stages:

- stage: 'PackageExtension'
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'

    workspace:
      clean: all

    steps:
    - powershell: 'scripts/save-vststasksdk-module.ps1'
      displayName: 'Download Required Powershell Modules'

    - task: TfxInstaller@2
      inputs:
        checkLatest: true
        
    - task: PackageAzureDevOpsExtension@2
      inputs:
        rootFolder: '$(System.DefaultWorkingDirectory)'
        outputPath: '$(Build.ArtifactStagingDirectory)/extension'
        extensionVersion: '$(Build.BuildNumber)'
        updateTasksVersion: true
        updateTasksVersionType: 'major'

    - publish: '$(Build.ArtifactStagingDirectory)/extension'
      artifact: 'extension'



- stage: 'PublishPrivateVersion'
  displayName: 'Publish Private Version Of Extension'
  dependsOn: 'PackageExtension'
  condition: succeeded()
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: none    # No need to checkout code. We're only using an artifact in this stage.
    
    - task: TfxInstaller@2
      inputs:
        checkLatest: true

    - download: current
      artifact: 'extension'
    
    - task: PublishAzureDevOpsExtension@2
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'Visual Studio Marketplace'
        fileType: 'vsix'
        vsixFile: '$(Pipeline.Workspace)/extension/*.vsix'
        extensionVersion: '$(Build.BuildNumber)'
        extensionVisibility: 'private_preview'
        extensionTag: '-preview'
        updateTasksId: true
        shareWith: '$(share-with-organization)'



- stage: 'PublishPublicVersion'
  displayName: 'Publish Release Version Of Extension'
  dependsOn: 'PublishPrivateVersion'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: none    # No need to checkout code. We're only using an artifact in this stage.
    
    - task: TfxInstaller@2
      inputs:
        checkLatest: true

    - download: current
      artifact: 'extension'
    
    - task: PublishAzureDevOpsExtension@2
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'Visual Studio Marketplace'
        fileType: 'vsix'
        vsixFile: '$(Pipeline.Workspace)/extension/*.vsix'
        extensionVersion: '$(Build.BuildNumber)'
        extensionVisibility: 'public'