# Using tasks from the 'Azure DevOps Extension Tasks' extension:
# https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks

trigger:
- master

stages:

- stage: 'PackageExtension'
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'

    workspace:
      clean: all

    steps:
    - task: TfxInstaller@2
      inputs:
        version: 'v0.6.x'
        
    - task: PackageAzureDevOpsExtension@2
      inputs:
        rootFolder: '$(System.DefaultWorkingDirectory)'
        outputPath: '$(Build.ArtifactStagingDirectory)/extension'
        updateTasksVersion: false

    - publish: '$(Build.ArtifactStagingDirectory)/extension'
      artifact: 'extension'